osx_image: xcode10.2
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=BetterLabel
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
script:
- set -o pipefail && xcodebuild test -scheme BetterLabel -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint
deploy:
  provider: releases
  api_key:
    secure: CPDJjn0FExGVXr6SvEmNFFb8pomXSMOAYPftocPIQUQq23ySG2NV9jYkS6LZ1oTuDhZwLGpZ55IVQQ132YpXGIVn/eltW91cfuuR9AgB4GopNY7ZeQ0jV7YxI1m0Y6IkO4M+H11FuL5wrytIiKj0TgXFne7cy85qYCWkO2TTTFYhtenZTvpJXfeoe9xlBWD92E/e3RCwwSIquJWpohDuBPxGYqKe3U/pPgKU0gLiHleQ3I5rZRPGGcp62C78mGwqLwUe/F1hjCVI4x0YfhgklmTVsjP5yM7Lcp+lbLSnAqYNyMJ9Y5SqZEBpqO90juVlsadcVBXPdRlQnREb0U1TymgdE3J/49R8xJn18va32UpmSUU0njMF3Y0VL+HmnmM+gRsW0Rj01+70MvgzRF657MkEUeorrw//12UG+SRTCLwmxDHOmLW3WHcliPuNX+sT5O8EbhgInl88IUP0ufUETIyXqu2k4nHE2IAV78EkV9s8as8l5dZDKql5tZRlw7fJ4HF/+Qjly0PfPp/6bG0OuojPkXU8tkq+q3vAzHRulCdw4hgbtf1WJNZroGDPOuEjhhwzdDTcP2rdAcIH7TYUW/nMQmhBnQLEKEDNab+6E/xWqhN4OdKCwhpi+UTeyIXUVKP0XH25mrnfFfdp8zgl9mO6gxlHkCdT/94q/hrSYA0=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: olejnjak/BetterLabel
    tags: true
after_deploy:
- pod trunk push
